version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tarea6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: actividad_db
    volumes:
      
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/03_migrate.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/04_reports.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/05_indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/06_roles.sql
    ports:
      - "5432:5432"

  web:  
    build: ./app-next
    container_name: nextjs_container
    ports:
      - "3000:3000"
    environment:
      # Conexi√≥n segura usando 'app_user' creado en roles.sql
      DATABASE_URL: postgres://app_user:secure_pass_123@db:5432/actividad_db
    volumes:
      
      - ./app-next:/app
      # Evita que se borren los node_modules del contenedor
      - /app/node_modules
    depends_on:
      - db