services:
  db:
    image: postgres:15-alpine
    container_name: tarea6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/03_migrate.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/04_reports.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/05_indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/06_roles.sql
    ports:
      - "5433:5432"

  web:  
    build: ./app-next
    container_name: nextjs_container
    ports:
      - "3000:3000"
    environment:
      
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      
      - ./app-next:/app
      - /app/node_modules
    depends_on:
      - db